export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/register',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  OAUTH_CALLBACK: '/api/auth/callback/:provider',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  ROLES: '/roles',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  SECURITY: '/settings/security',
  LOGIN_HISTORY: '/settings/login-history',
  API_TOKENS: '/settings/api-tokens',
  PREFERENCES: '/settings/preferences',
  PROFILE_EDIT: '/profile/edit',
  PROFILE_VIEW: '/profile/:userId',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_PLATFORM_ADMINS: '/admin/platform-admins',
  ADMIN_ACCEPT_INVITE: '/admin/accept-invite',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: '/admin/users/:userId',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  // ─── Public site routes (public, no auth) ───────────────────────────────────
  HOW_IT_WORKS: '/how-it-works',
  CURRICULUM: '/curriculum',
  PRICING: '/pricing',
  ABOUT: '/about',
  SECURITY_TRUST: '/security',
  CONTACT: '/contact',
  FOR_INSTITUTIONS: '/for-institutions',
  FAQ: '/faq',
  // ─── Secondary site pages (footer destinations, no orphans) ───────────────
  CAREERS: '/careers',
  DOCUMENTATION: '/docs',
  MODULE_CATALOG: '/catalog',
  LEARNING_PATH: '/learning-path',
  INSTRUCTOR_TOOLS: '/instructor-tools',
  PRIVACY: '/privacy',
  TERMS: '/terms',
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
