export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/register',
  VERIFY_EMAIL: '/verify-email',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  OAUTH_CALLBACK: '/api/auth/callback/:provider',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  ROLES: '/roles',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  SECURITY: '/settings/security',
  LOGIN_HISTORY: '/settings/login-history',
  API_TOKENS: '/settings/api-tokens',
  PREFERENCES: '/settings/preferences',
  PROFILE_EDIT: '/profile/edit',
  PROFILE_VIEW: '/profile/:userId',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_PLATFORM_ADMINS: '/admin/platform-admins',
  ADMIN_ACCEPT_INVITE: '/admin/accept-invite',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAIL: '/admin/users/:userId',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  ADMIN_ORGANIZATIONS: '/admin/organizations',
  ADMIN_ORGANIZATION_DETAIL: '/admin/organizations/:orgId',
  // ─── F3 organization workspace (OrgAdminShell) ──────────────────────────────
  ORG_DASHBOARD: '/org/dashboard',
  ORG_CLASSES: '/org/classes',
  ORG_CLASS_NEW: '/org/classes/new',
  ORG_CLASS_DETAIL: '/org/classes/:classId',
  ORG_CLASS_ROSTER: '/org/classes/:classId/students',
  ORG_CLASS_INVITE: '/org/classes/:classId/invite',
  ORG_PROFESSORS: '/org/professors',
  ORG_SETTINGS: '/org/settings',
  // ─── F3 enrollment (student + invitation accept) ────────────────────────────
  ENROLL_ACCEPT: '/enroll/accept',
  STUDENT_MY_CLASS: '/student/class',
  // ─── Public site routes (public, no auth) ───────────────────────────────────
  HOW_IT_WORKS: '/how-it-works',
  CURRICULUM: '/curriculum',
  PRICING: '/pricing',
  ABOUT: '/about',
  SECURITY_TRUST: '/security',
  CONTACT: '/contact',
  FOR_INSTITUTIONS: '/for-institutions',
  FAQ: '/faq',
  // ─── Secondary site pages (footer destinations, no orphans) ───────────────
  CAREERS: '/careers',
  DOCUMENTATION: '/docs',
  MODULE_CATALOG: '/catalog',
  LEARNING_PATH: '/learning-path',
  INSTRUCTOR_TOOLS: '/instructor-tools',
  PRIVACY: '/privacy',
  TERMS: '/terms',
} as const;

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
